"""
check_recall_overlap.py
Week 13 — Phase A Data Rebuild

ori_pqal.json has exactly 1000 questions, all assigned to:
  - val set: 200 questions
  - test set: 800 questions

The original recall sample (seed=42, 50 from all 1000) overlapped
entirely with the test set — contaminated.

FIX: Sample 50 recall IDs from the VAL set only (200 questions).
Val set is safe to use for recall evaluation because it is never
used in the main 800-question experiment.

Output: data/pubmedqa/processed/recall_ids.json
Report: docs/recall_test_overlap_check.txt
"""

import json
import os
import random

_base          = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBMEDQA_PATH  = os.path.join(_base, "data", "pubmedqa", "raw", "ori_pqal.json")
TEST_IDS_PATH  = os.path.join(_base, "data", "pubmedqa", "processed", "test_ids.json")
VAL_IDS_PATH   = os.path.join(_base, "data", "pubmedqa", "processed", "val_ids.json")
RECALL_IDS_OUT = os.path.join(_base, "data", "pubmedqa", "processed", "recall_ids.json")
OUT_PATH       = os.path.join(_base, "docs", "recall_test_overlap_check.txt")

NUM_QUESTIONS = 50
RANDOM_SEED   = 42

# Load all IDs
print("Loading ori_pqal.json ...")
with open(PUBMEDQA_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)
print(f"  Total questions in ori_pqal.json: {len(data)}")

print("Loading test_ids.json ...")
with open(TEST_IDS_PATH, "r", encoding="utf-8") as f:
    test_ids = set(json.load(f))
print(f"  Test set size: {len(test_ids)}")

print("Loading val_ids.json ...")
with open(VAL_IDS_PATH, "r", encoding="utf-8") as f:
    val_ids_list = json.load(f)
val_ids = set(val_ids_list)
print(f"  Val set size: {len(val_ids)}")

# Check original overlap (document what went wrong)
random.seed(RANDOM_SEED)
original_recall_ids = set(random.sample(list(data.keys()), NUM_QUESTIONS))
original_overlap = original_recall_ids & test_ids
print(f"\nOriginal overlap (seed=42 from all 1000): {len(original_overlap)} IDs")
print(f"  → All 1000 questions are in val+test. No separate pool exists.")

# FIX: Sample 50 from val set only
random.seed(99)
clean_recall_ids = random.sample(val_ids_list, NUM_QUESTIONS)
clean_overlap = set(clean_recall_ids) & test_ids

assert len(clean_overlap) == 0, "ERROR: Still overlapping with test set!"
print(f"\n✅ Clean recall sample: {len(clean_recall_ids)} IDs from val set")
print(f"   Overlap with test set: {len(clean_overlap)} (ZERO confirmed)")

# Save clean recall IDs
os.makedirs(os.path.dirname(RECALL_IDS_OUT), exist_ok=True)
with open(RECALL_IDS_OUT, "w", encoding="utf-8") as f:
    json.dump(clean_recall_ids, f, indent=2)
print(f"✅ Saved to: {RECALL_IDS_OUT}")

# Write report
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("Recall / Test Set Overlap Check\n")
    f.write("=" * 50 + "\n\n")
    f.write(f"Total questions in ori_pqal.json : {len(data)}\n")
    f.write(f"Val set size                     : {len(val_ids)}\n")
    f.write(f"Test set size                    : {len(test_ids)}\n")
    f.write(f"Remaining pool after val+test    : 0\n\n")
    f.write("PROBLEM IDENTIFIED:\n")
    f.write("  Original recall sample (seed=42, 50 from all 1000 IDs)\n")
    f.write(f"  overlapped with test set: {len(original_overlap)}/50 IDs contaminated.\n")
    f.write("  ori_pqal.json has exactly 1000 questions — all assigned\n")
    f.write("  to val (200) or test (800). No separate pool exists.\n\n")
    f.write("FIX APPLIED:\n")
    f.write("  Recall evaluation now samples 50 IDs from the VAL set only.\n")
    f.write("  Val set is safe: it is used only for grid search weight tuning,\n")
    f.write("  never for the main 800-question experiment.\n")
    f.write(f"  New sample: seed=99, 50 from {len(val_ids)} val IDs\n")
    f.write(f"  Overlap with test set: {len(clean_overlap)} (ZERO CONFIRMED)\n\n")
    f.write("RESULT: CLEAN. recall_ids.json saved.\n")
    f.write("evaluate_recall.py must load recall_ids.json going forward.\n\n")
    f.write("Generated by: src/check_recall_overlap.py\n")

print(f"\nReport written to: {OUT_PATH}")
print("\n✅ check_recall_overlap.py complete!")